// Code generated by go generate; DO NOT EDIT.
// This file was generated on 2018-09-26 21:36:31.595796501 &#43;0200 CEST m=&#43;11.490609586
// using data from /Users/pedro/Documents/www/webapp-react
package acl

import (
	"regexp"
	"sort"
)

func init() {
	isPublicRoute = regexp.MustCompile("(^\\/welcome$|^\\/admin\\/activate$|^\\/error$)")
	isValidRoute = regexp.MustCompile("(^\\/signal\\/team\\/cycle-time\\/(\\w+)?$|^\\/signal\\/team\\/issues-closed\\/(\\w+)?$|^\\/data\\/team\\/issues-open$|^\\/data\\/person\\/issues-worked$|^\\/data\\/person\\/rework-rate$|^\\/languages$|^\\/signal\\/person\\/commits\\/(\\w+)?$|^\\/performance\\/people\\/(\\w+)?\\/(\\w+)?$|^\\/signal\\/team\\/cost\\/(\\w+)?$|^\\/signal\\/team\\/cycle-time\\/data\\/(\\w+)?$|^\\/performance\\/team\\/(\\w+)?$|^\\/signal\\/team\\/sprint-volatility\\/(\\w+)?$|^\\/data\\/person\\/commits$|^\\/signal\\/person\\/changes-per-commit\\/(\\w+)?$|^\\/jira\\/(\\w+)?$|^\\/performance\\/location$|^\\/signal\\/team\\/scheduled-rate\\/(\\w+)?$|^\\/data\\/team\\/sprints-completed$|^\\/admin\\/mapping$|^$|^\\/welcome$|^\\/signal\\/team\\/initiative-issues\\/(\\w+)?$|^\\/work-forecast\\/(\\w+)?\\/(\\w+)?\\/(\\w+)?\\/(\\w+)?\\/(\\w+)?$|^\\/data\\/team\\/issues-completed$|^\\/admin\\/activate$|^\\/admin\\/people$|^\\/signal\\/team\\/defects-density\\/(\\w+)?$|^\\/performance-detail\\/team\\/(\\w+)?$|^\\/data\\/person\\/traceability$|^\\/admin\\/roles$|^\\/signal\\/person\\/issues-worked\\/(\\w+)?$|^\\/error$|^\\/signal\\/person\\/cycle-time\\/(\\w+)?$|^\\/performance-detail\\/people\\/(\\w+)?$|^\\/signal\\/person\\/rework-rate\\/(\\w+)?$|^\\/signal\\/team\\/defects-rate\\/(\\w+)?$|^\\/signal\\/team\\/delivered-vs-committed\\/(\\w+)?$|^\\/signal\\/team\\/innovation-rate\\/(\\w+)?$|^\\/$|^\\/data\\/team\\/cost$|^\\/admin$|^\\/admin\\/cost-center$|^\\/signal\\/team\\/rework-rate\\/(\\w+)?$|^\\/signal\\/team\\/backlog-change\\/(\\w+)?$|^\\/signal\\/person\\/traceability\\/(\\w+)?$|^\\/signal\\/person\\/code-ownership\\/(\\w+)?$)")
	routes = []*Route{
		&Route{
			Name:           "TeamCycleTime",
			Path:	        "/signal/team/cycle-time/:id",
			Title:          "Team - Cycle Time",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "TeamIssuesClosed",
			Path:	        "/signal/team/issues-closed/:id",
			Title:          "Team - Closed Issues",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "DataIssuesOpen",
			Path:	        "/data/team/issues-open",
			Title:          "Data - Issues Open",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "DataIssuesWorked",
			Path:	        "/data/person/issues-worked",
			Title:          "Data - Issues Worked",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "DataReworkPercent",
			Path:	        "/data/person/rework-rate",
			Title:          "Data - Rework Rate",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "Languages",
			Path:	        "/languages",
			Title:          "Technology - Languages",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "Contributions by programming language for people and projects",
			
		},
		&Route{
			Name:           "PersonCommits",
			Path:	        "/signal/person/commits/:id",
			Title:          "People - Commits",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "PersonPerformance",
			Path:	        "/performance/people/:filter/:id",
			Title:          "People - Performance Summary",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "Compare employees across a range of signals",
			
		},
		&Route{
			Name:           "TeamCost",
			Path:	        "/signal/team/cost/:id",
			Title:          "Team - Cost",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "TeamCycleTimeData",
			Path:	        "/signal/team/cycle-time/data/:id",
			Title:          "Team - Cycle Time Data",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "TeamPerformance",
			Path:	        "/performance/team/:team",
			Title:          "Team - Performance Summary",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "Compare teams across a range of signals",
			
		},
		&Route{
			Name:           "TeamSprintVolatility",
			Path:	        "/signal/team/sprint-volatility/:id",
			Title:          "Team - Sprint Volatility",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "DataCommits",
			Path:	        "/data/person/commits",
			Title:          "Data - Commits",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "PersonChangesPerCommit",
			Path:	        "/signal/person/changes-per-commit/:id",
			Title:          "People - Changes Per Commit",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "Jira",
			Path:	        "/jira/:team",
			Title:          "Technology - Jira",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "Usage and adoption data for all Jira projects",
			
		},
		&Route{
			Name:           "LocationPerformance",
			Path:	        "/performance/location",
			Title:          "Location Performance",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "Compare locations across a range of signals",
			
		},
		&Route{
			Name:           "TeamScheduled",
			Path:	        "/signal/team/scheduled-rate/:id",
			Title:          "Team - Planned Issues",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "DataSprintsCompleted",
			Path:	        "/data/team/sprints-completed",
			Title:          "Data - Sprints Completed",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "AdminMapping",
			Path:	        "/admin/mapping",
			Title:          "Team Mapping",
			Public:         false,
			Hidden:         false,
			Admin:          true,
			Description:    "Associate projects and code repositories with teams",
			
		},
		&Route{
			Name:           "Cost - Salary Information",
			Path:	        "",
			Title:          "Salaries",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "Disabling salary data will remove salary and cost data from all views, including 2x2 cost oriented matrixes",
			
		},
		&Route{
			Name:           "Welcome",
			Path:	        "/welcome",
			Title:          "Welcome",
			Public:         true,
			Hidden:         true,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "TeamStrategicPercent",
			Path:	        "/signal/team/initiative-issues/:id",
			Title:          "Team - Strategic Issues",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "WorkSummary",
			Path:	        "/work-forecast/:team/:issueType/:priority/:id/:customField",
			Title:          "Work Forecast",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "Status and estimates for open issues",
			
		},
		&Route{
			Name:           "DataIssuesCompleted",
			Path:	        "/data/team/issues-completed",
			Title:          "Data - Issues Completed",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "AdminActivate",
			Path:	        "/admin/activate",
			Title:          "Admin Activation",
			Public:         true,
			Hidden:         true,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "AdminPeople",
			Path:	        "/admin/people",
			Title:          "People",
			Public:         false,
			Hidden:         false,
			Admin:          true,
			Description:    "Manage your users",
			
		},
		&Route{
			Name:           "TeamDefectsDensity",
			Path:	        "/signal/team/defects-density/:id",
			Title:          "Team - Defect Density",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "TeamPerformanceDetail",
			Path:	        "/performance-detail/team/:team",
			Title:          "Team - Performance Detail",
			Public:         false,
			Hidden:         true,
			Admin:          false,
			Description:    "Detailed performance signals for a specific team",
			
		},
		&Route{
			Name:           "DataTraceability",
			Path:	        "/data/person/traceability",
			Title:          "Data - Traceability",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "AdminRoles",
			Path:	        "/admin/roles",
			Title:          "Roles",
			Public:         false,
			Hidden:         false,
			Admin:          true,
			Description:    "Create and manage roles",
			
		},
		&Route{
			Name:           "PersonIssuesWorked",
			Path:	        "/signal/person/issues-worked/:id",
			Title:          "People - Issues Worked",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "Error",
			Path:	        "/error",
			Title:          "Error",
			Public:         true,
			Hidden:         true,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "PersonCycleTime",
			Path:	        "/signal/person/cycle-time/:id",
			Title:          "People - Cycle Time",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "PersonPerformanceDetail",
			Path:	        "/performance-detail/people/:person",
			Title:          "People - Performance Detail",
			Public:         false,
			Hidden:         true,
			Admin:          false,
			Description:    "Detailed performance signals for a specific person",
			
		},
		&Route{
			Name:           "PersonReworkPercent",
			Path:	        "/signal/person/rework-rate/:id",
			Title:          "People - Rework Rate",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "TeamDefectsPercent",
			Path:	        "/signal/team/defects-rate/:id",
			Title:          "Team - Defect Rate",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "TeamDeliveredVsCommitted",
			Path:	        "/signal/team/delivered-vs-committed/:id",
			Title:          "Team - Delivered vs. Planned",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "TeamNewFeatures",
			Path:	        "/signal/team/innovation-rate/:id",
			Title:          "Team - Innovation Rate",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "Main",
			Path:	        "/",
			Title:          "",
			Public:         false,
			Hidden:         true,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "DataCost",
			Path:	        "/data/team/cost",
			Title:          "Data - Cost",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "Admin",
			Path:	        "/admin",
			Title:          "",
			Public:         false,
			Hidden:         true,
			Admin:          true,
			Description:    "",
			
		},
		&Route{
			Name:           "AdminCostCenters",
			Path:	        "/admin/cost-center",
			Title:          "Cost Centers",
			Public:         false,
			Hidden:         false,
			Admin:          true,
			Description:    "Create and manage cost centers",
			
		},
		&Route{
			Name:           "TeamReworkPercent",
			Path:	        "/signal/team/rework-rate/:id",
			Title:          "Team - Rework Rate",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "TeamBacklogChangePercent",
			Path:	        "/signal/team/backlog-change/:id",
			Title:          "Team - Backlog Change",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "PersonTraceability",
			Path:	        "/signal/person/traceability/:id",
			Title:          "People - Traceability",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
		&Route{
			Name:           "PersonCodeOwnership",
			Path:	        "/signal/person/code-ownership/:id",
			Title:          "People - Code Ownership",
			Public:         false,
			Hidden:         false,
			Admin:          false,
			Description:    "",
			
		},
	}
	// sort the routes by path to be consistent
	sort.Slice(routes, func(i, j int) bool {
		return routes[i].Name < routes[j].Name
	})
	// initialize the route data
	for _, route := range routes {
		if route.Auth != nil {
			for name, feature := range route.Auth.Features {
				feature.name = name
				feature.route = route
			}
		}
	}
}